// ============================================================================
// BOOK 1 - GOOGLE EARTH ENGINE FEATURE EXPORT
// Project: Low-cost remote-sensing detection of Chinese urban villages
// Author: Entao Wang
//
// What this script does:
//   This is the Earth observation feature factory for the project. It runs in
//   the Google Earth Engine Code Editor and exports one CSV per city. Each row
//   is a 250 m grid cell; each column is a remote-sensing or urban-context
//   feature that is later consumed by Book 2 in Colab.
//
// Inputs:
//   - Urban-core AOI asset generated by the pre-process notebook.
//   - Sentinel-2 SR Harmonized imagery.
//   - Sentinel-1 GRD imagery.
//   - ESA WorldCover 2021 v200.
//
// Outputs:
//   - Drive CSV files named book1_grid_features_{city}_{year}.csv.
//
// Expected runtime:
//   City exports are scheduled as Earth Engine Tasks. Small cities usually
//   finish in minutes; large AOIs can take longer depending on GEE load.
//
// Methodological notes:
//   1. City-specific UTM projections are used so 250 m grids have comparable
//      ground size across Guangzhou, Beijing, Shanghai, and the other cities.
//   2. Quarterly Sentinel-2 composites preserve seasonal stability signals
//      that distinguish stable built-up fabric from vegetation-dominated areas.
//   3. Sentinel-1 ascending and descending passes are kept separate because
//      viewing geometry can change urban backscatter.
//   4. SWIR GLCM texture is used because SWIR bands carry stronger information
//      about built materials than visible greyscale texture.
//   5. OSM candidate features are deliberately not attached here by default;
//      Book 2 attaches them in Colab and uses them only for weak labels.
// ============================================================================

// ----------------------------- USER SETTINGS --------------------------------
// This block controls the export year, grid size, target cities, and AOI asset.
// Change these settings before pressing Run in the GEE Code Editor.

var YEAR = 2025;
var GRID_SIZE_M = 250;

// GEE's Drive export folder is a folder name, not a robust nested path.
// Create this folder in Drive before exporting:
// MyDrive/0069/week10/book1_gee_exports
var EXPORT_FOLDER = 'book1_gee_exports';

// Export mode. In final production mode, schedule all cities at once and start
// them from the Tasks tab. For debugging, export a single city first.
var EXPORT_ALL_CITIES = ture;
var SINGLE_CITY = 'chongqing';

var TRAIN_CITIES = ['guangzhou', 'shenzhen', 'tianjin', 'beijing'];
var TEST_CITIES = ['xian', 'dongguan', 'shanghai', 'chengdu', 'chongqing', 'wuhan'];
var ALL_CITIES = TRAIN_CITIES.concat(TEST_CITIES);
var CITIES_TO_EXPORT = EXPORT_ALL_CITIES ? ALL_CITIES : [SINGLE_CITY];

// AOI source. Run pre-process/prepare_urban_aoi_from_gadm_l3.ipynb in Colab
// once to generate urban_cores_by_builtup_shp.zip, then upload it to GEE
// Assets. The asset stores one feature per retained Level-3 district. Districts
// were retained only if their WorldCover built-up fraction was at least 0.20,
// which removes oversized rural/mountain parts of full municipalities.
//
// boundaryFc.filter(eq('city', cityName)).geometry() automatically unions
// all matching district polygons into one multi-polygon city AOI.
var USE_BOUNDARY_ASSET = true;
var CITY_BOUNDARY_ASSET = 'projects/zcfaew0/assets/0069/urban_cores_by_builtup';
var CITY_NAME_FIELD = 'city';

// No longer needed: the new urban-cores asset is already small enough.
// Leaving as a no-op fallback for safety. If you want extra clipping (eg to
// drop a specific peripheral district), turn this back on.
var CLIP_BOUNDARY_ASSET_TO_CORE_BBOX = false;

// Optional OSM mode. Keep this false for the final workflow: OSM candidates are
// the weak-label source and are attached in Book 2, not exported as EO inputs.
var USE_OSM_CANDIDATES = false;
// var OSM_CANDIDATES_ASSET = 'users/your_username/osm_urban_village_candidates';

// Export-size filter only. This is not the final label rule. We keep a grid if
// it has either some built-up signal or enough surrounding urban context:
//   builtup_mean >= 0.02 (any built-up presence)            -- catches urban
//   OR urban_surrounding_1km >= 0.40 (in urban context)     -- catches urban green
// This preserves urban green for the 3-class problem in Book 2.
var MIN_BUILTUP_FRACTION_FOR_EXPORT = 0.02;
var MIN_URBAN_CONTEXT_FOR_EXPORT = 0.40;

// ----------------------------- CITY METADATA --------------------------------
// Bounding boxes are retained as computational fallbacks and for map previews.
// The final AOI normally comes from the uploaded urban-core boundary asset.

var cityBBoxes = {
  guangzhou: ee.Geometry.Rectangle([112.95, 22.95, 113.75, 23.55], null, false),
  shenzhen: ee.Geometry.Rectangle([113.70, 22.35, 114.65, 22.90], null, false),
  tianjin: ee.Geometry.Rectangle([116.70, 38.75, 117.90, 39.55], null, false),
  beijing: ee.Geometry.Rectangle([115.85, 39.55, 117.15, 40.45], null, false),
  dongguan: ee.Geometry.Rectangle([113.45, 22.65, 114.35, 23.20], null, false),
  shanghai: ee.Geometry.Rectangle([120.85, 30.65, 122.15, 31.90], null, false),
  chongqing: ee.Geometry.Rectangle([106.15, 29.20, 107.05, 30.05], null, false),
  xian: ee.Geometry.Rectangle([108.65, 33.95, 109.35, 34.55], null, false),
  wuhan: ee.Geometry.Rectangle([113.70, 30.25, 115.10, 31.00], null, false),
  chengdu: ee.Geometry.Rectangle([103.65, 30.35, 104.55, 31.05], null, false)
};

// City-specific UTM zones. These projections make the 250 m grid physically
// comparable across cities at different latitudes.
var cityUtmEpsg = {
  guangzhou: 'EPSG:32649',
  shenzhen: 'EPSG:32649',
  tianjin: 'EPSG:32650',
  beijing: 'EPSG:32650',
  dongguan: 'EPSG:32649',
  shanghai: 'EPSG:32651',
  chongqing: 'EPSG:32648',
  xian: 'EPSG:32649',
  wuhan: 'EPSG:32650',
  chengdu: 'EPSG:32648'
};

// ----------------------------- HELPER FUNCTIONS -----------------------------
// The helper functions below are written as reusable processing blocks. Each
// city export calls the same functions, which keeps the feature definitions
// consistent across all train and test cities.

function getCityGeometry(cityName) {
  // Purpose: return the study geometry for a city.
  // Input: a lowercase city key such as 'guangzhou'.
  // Output: either the uploaded urban-core boundary geometry or the fallback
  // bounding box geometry.
  var geom = cityBBoxes[cityName];

  if (USE_BOUNDARY_ASSET) {
    var boundaryFc = ee.FeatureCollection(CITY_BOUNDARY_ASSET)
      .filter(ee.Filter.eq(CITY_NAME_FIELD, cityName));
    geom = boundaryFc.geometry();

    if (CLIP_BOUNDARY_ASSET_TO_CORE_BBOX) {
      geom = geom.intersection(cityBBoxes[cityName], 1);
    }
  }

  return geom;
}

function maskS2Clouds(img) {
  // Purpose: remove Sentinel-2 cloud, cloud shadow, cirrus, and snow/ice pixels
  // using the Scene Classification Layer. The image is also scaled from integer
  // reflectance to surface reflectance in [0, 1].
  var scl = img.select('SCL');
  var clear = scl.neq(3)      // cloud shadow
    .and(scl.neq(8))          // medium cloud
    .and(scl.neq(9))          // high cloud
    .and(scl.neq(10))         // cirrus
    .and(scl.neq(11));        // snow / ice

  return img.updateMask(clear).divide(10000)
    .copyProperties(img, ['system:time_start']);
}

function addS2Indices(img) {
  // Purpose: add spectral indices commonly used in urban and vegetation
  // mapping. NDVI captures vegetation, NDBI captures built-up tendency, NDWI
  // captures water/moisture, and BSI captures bare-soil/built-up contrast.
  var ndvi = img.normalizedDifference(['B8', 'B4']).rename('ndvi');
  var ndbi = img.normalizedDifference(['B11', 'B8']).rename('ndbi');
  var ndwi = img.normalizedDifference(['B3', 'B8']).rename('ndwi');
  var bsi = img.expression(
    '((swir + red) - (nir + blue)) / ((swir + red) + (nir + blue))',
    {
      swir: img.select('B11'),
      red: img.select('B4'),
      nir: img.select('B8'),
      blue: img.select('B2')
    }
  ).rename('bsi');

  return img.addBands([ndvi, ndbi, ndwi, bsi]);
}

function s2Composite(region, startDate, endDate) {
  // Purpose: create one cloud-masked Sentinel-2 median composite for a date
  // window and add the spectral indices used downstream.
  // Output: a clipped multi-band image over the city AOI.
  var composite = ee.ImageCollection('COPERNICUS/S2_SR_HARMONIZED')
    .filterBounds(region)
    .filterDate(startDate, endDate)
    .filter(ee.Filter.lt('CLOUDY_PIXEL_PERCENTAGE', 70))
    .map(maskS2Clouds)
    .select(['B2', 'B3', 'B4', 'B8', 'B11', 'B12'])
    .median()
    .clip(region);

  return addS2Indices(composite);
}

function prefixBands(img, prefix) {
  // Purpose: add a stable prefix to image bands so annual, quarterly, SAR, and
  // context features can coexist without name collisions after concatenation.
  var names = img.bandNames();
  var newNames = names.map(function(name) {
    return ee.String(prefix).cat('_').cat(ee.String(name));
  });
  return img.rename(newNames);
}

function makeGrid(region, cityName, gridSizeMeters) {
  // Purpose: create vector grid cells in a city-specific UTM CRS. This avoids
  // the scale distortion that would occur with Web Mercator.
  // Output: a FeatureCollection of 250 m grid polygons with city metadata.
  var proj = ee.Projection(cityUtmEpsg[cityName]).atScale(gridSizeMeters);
  var coords = ee.Image.pixelCoordinates(proj).select(['x', 'y']);

  // pixelCoordinates(proj) already returns coordinates in the pixel grid of
  // the 250m UTM projection. Do not divide by gridSizeMeters again; doing so
  // turns the intended 250m grid into ~62.5km cells.
  var gridId = coords.select('x').toInt64()
    .multiply(10000000)
    .add(coords.select('y').toInt64())
    .rename('grid_id');

  var grid = gridId.reduceToVectors({
    geometry: region,
    crs: proj,
    scale: gridSizeMeters,
    geometryType: 'polygon',
    eightConnected: false,
    labelProperty: 'grid_id',
    reducer: ee.Reducer.countEvery(),
    maxPixels: 1e13
  });

  return grid.map(function(f) {
    return f.intersection(region, 1).set({
      city: cityName,
      year: YEAR,
      grid_size_m: gridSizeMeters,
      grid_crs: cityUtmEpsg[cityName]
    });
  });
}

function s1PassComposite(region, startDate, endDate, passName, prefix) {
  // Purpose: build a Sentinel-1 composite for one orbit direction. Ascending
  // and descending passes are processed separately because SAR backscatter over
  // urban fabric is sensitive to viewing geometry.
  // Output: VV, VH, VV-VH, VV texture, and a has-data flag for that pass.
  var collection = ee.ImageCollection('COPERNICUS/S1_GRD')
    .filterBounds(region)
    .filterDate(startDate, endDate)
    .filter(ee.Filter.eq('instrumentMode', 'IW'))
    .filter(ee.Filter.eq('orbitProperties_pass', passName))
    .filter(ee.Filter.listContains('transmitterReceiverPolarisation', 'VV'))
    .filter(ee.Filter.listContains('transmitterReceiverPolarisation', 'VH'))
    .select(['VV', 'VH']);

  // Some cities may only have one useful S1 orbit direction after filtering.
  // If this pass is empty, return masked VV/VH bands instead of crashing.
  var empty = ee.Image.constant([0, 0])
    .rename(['VV', 'VH'])
    .updateMask(ee.Image.constant(0))
    .clip(region);

  var img = ee.Image(
    ee.Algorithms.If(
      collection.size().gt(0),
      collection.median().clip(region),
      empty
    )
  );

  var vv = img.select('VV').rename(prefix + '_vv');
  var vh = img.select('VH').rename(prefix + '_vh');
  var ratio = img.select('VV').subtract(img.select('VH')).rename(prefix + '_vv_minus_vh');
  var texture = img.select('VV')
    .reduceNeighborhood({
      reducer: ee.Reducer.stdDev(),
      kernel: ee.Kernel.square({radius: 45, units: 'meters'})
    })
    .rename(prefix + '_vv_texture_90m');

  var hasData = ee.Image.constant(
    ee.Number(ee.Algorithms.If(collection.size().gt(0), 1, 0))
  ).rename(prefix + '_has_data').clip(region);

  return ee.Image.cat([vv, vh, ratio, texture, hasData]);
}

function buildFeatureImage(region) {
  // Purpose: assemble the complete raster feature stack for one city before
  // reducing it to grid-level statistics.
  // Output: a multi-band image containing annual/quarterly Sentinel-2 features,
  // Sentinel-1 features, WorldCover context, and urban-context features.
  var annualStart = ee.Date.fromYMD(YEAR, 1, 1);
  var annualEnd = ee.Date.fromYMD(YEAR, 12, 31);

  var s2AnnualRaw = s2Composite(region, annualStart, annualEnd);
  var s2Annual = prefixBands(
    s2AnnualRaw.select(['B2', 'B3', 'B4', 'B8', 'B11', 'B12', 'ndvi', 'ndbi', 'ndwi', 'bsi']),
    's2'
  );

  var q1 = s2Composite(region, ee.Date.fromYMD(YEAR, 1, 1), ee.Date.fromYMD(YEAR, 3, 31))
    .select(['ndvi', 'ndbi']).rename(['q1_ndvi', 'q1_ndbi']);
  var q2 = s2Composite(region, ee.Date.fromYMD(YEAR, 4, 1), ee.Date.fromYMD(YEAR, 6, 30))
    .select(['ndvi', 'ndbi']).rename(['q2_ndvi', 'q2_ndbi']);
  var q3 = s2Composite(region, ee.Date.fromYMD(YEAR, 7, 1), ee.Date.fromYMD(YEAR, 9, 30))
    .select(['ndvi', 'ndbi']).rename(['q3_ndvi', 'q3_ndbi']);
  var q4 = s2Composite(region, ee.Date.fromYMD(YEAR, 10, 1), ee.Date.fromYMD(YEAR, 12, 31))
    .select(['ndvi', 'ndbi']).rename(['q4_ndvi', 'q4_ndbi']);

  var ndviQuarterlyStd = ee.ImageCollection([
    q1.select('q1_ndvi').rename('ndvi'),
    q2.select('q2_ndvi').rename('ndvi'),
    q3.select('q3_ndvi').rename('ndvi'),
    q4.select('q4_ndvi').rename('ndvi')
  ]).reduce(ee.Reducer.stdDev()).rename('ndvi_quarterly_std');

  var ndbiQuarterlyStd = ee.ImageCollection([
    q1.select('q1_ndbi').rename('ndbi'),
    q2.select('q2_ndbi').rename('ndbi'),
    q3.select('q3_ndbi').rename('ndbi'),
    q4.select('q4_ndbi').rename('ndbi')
  ]).reduce(ee.Reducer.stdDev()).rename('ndbi_quarterly_std');

  // GLCM texture is computed on SWIR (B11), not on RGB-gray. Reasons:
  //   - SWIR is more sensitive to building materials (concrete, metal, asphalt)
  //   - SWIR has more dynamic range than visible bands over urban surfaces
  //   - RGB-gray was getting compressed into [12, 80] / 256 levels, killing GLCM contrast
  // size=9 (90m kernel) matches SAR texture scale.
  var swirGray = s2AnnualRaw.select('B11')
    .multiply(1000)
    .clamp(0, 255)
    .toUint8()
    .rename('s2_swir_gray');
  var glcm = swirGray.glcmTexture({size: 9});
  var s2Texture = ee.Image.cat([
    glcm.select('s2_swir_gray_contrast').rename('s2_swir_glcm_contrast'),
    glcm.select('s2_swir_gray_ent').rename('s2_swir_glcm_entropy'),
    s2AnnualRaw.select('ndbi')
      .reduceNeighborhood({
        reducer: ee.Reducer.stdDev(),
        kernel: ee.Kernel.square({radius: 45, units: 'meters'})
      })
      .rename('s2_ndbi_texture_90m')
  ]);

  var s1Asc = s1PassComposite(region, annualStart, annualEnd, 'ASCENDING', 's1_asc');
  var s1Desc = s1PassComposite(region, annualStart, annualEnd, 'DESCENDING', 's1_desc');

  var worldcover = ee.ImageCollection('ESA/WorldCover/v200')
    .first()
    .select('Map')
    .clip(region);

  var builtup = worldcover.eq(50).rename('builtup');
  var vegetation = worldcover.eq(10)
    .or(worldcover.eq(20))
    .or(worldcover.eq(30))
    .or(worldcover.eq(40))
    .or(worldcover.eq(95))
    .rename('vegetation');
  var water = worldcover.eq(80).rename('water');

  var urbanContext1km = builtup
    .reduceNeighborhood({
      reducer: ee.Reducer.mean(),
      kernel: ee.Kernel.circle({radius: 1000, units: 'meters'})
    })
    .rename('urban_surrounding_1km');

  // Note: built-up edge density via Canny is intentionally dropped. The signal
  // it carried is redundant with s2_ndvi_stdDev (per-grid NDVI spread) and
  // s2_ndbi_texture_90m (NDBI std at 90m). It was also semantically inverted
  // at WorldCover 10m: urban villages (alleys < 10m) appear as continuous
  // built-up with LOW edge density, formal residential with internal greenery
  // has HIGH edge density. Better to rely on direct heterogeneity features.

  return ee.Image.cat([
    s2Annual,
    q1, q2, q3, q4,
    ndviQuarterlyStd,
    ndbiQuarterlyStd,
    s2Texture,
    s1Asc,
    s1Desc,
    builtup,
    vegetation,
    water,
    urbanContext1km
  ]);
}

function exportCity(cityName, drawPreview) {
  // Purpose: run the full feature extraction workflow for one city and schedule
  // a Drive CSV export. The first city is also drawn on the map for inspection.
  // Output: one Earth Engine export task named book1_grid_features_{city}_{year}.
  var cityGeometry = getCityGeometry(cityName);
  var featureImage = buildFeatureImage(cityGeometry);

  var grid = makeGrid(cityGeometry, cityName, GRID_SIZE_M);

  var reducer = ee.Reducer.mean()
    .combine({reducer2: ee.Reducer.stdDev(), sharedInputs: true});

  var gridFeatures = featureImage.reduceRegions({
    collection: grid,
    reducer: reducer,
    scale: 10,
    tileScale: 4
  });

  // Keep a grid if it has ANY built-up presence OR it is in an urban
  // surrounding (>= 0.40). The OR clause preserves urban green for the
  // 3-class problem in Book 2.
  gridFeatures = gridFeatures.filter(
    ee.Filter.or(
      ee.Filter.gte('builtup_mean', MIN_BUILTUP_FRACTION_FOR_EXPORT),
      ee.Filter.gte('urban_surrounding_1km_mean', MIN_URBAN_CONTEXT_FOR_EXPORT)
    )
  );

  if (USE_OSM_CANDIDATES) {
    var osmCandidates = ee.FeatureCollection(OSM_CANDIDATES_ASSET)
      .filterBounds(cityGeometry);
    var osmUnion = osmCandidates.geometry(1);

    gridFeatures = gridFeatures.map(function(f) {
      var geom = f.geometry();
      var area = geom.area(1);
      var overlapArea = geom.intersection(osmUnion, 1).area(1);
      return f.set({
        osm_candidate_overlap: overlapArea.divide(area),
        dist_to_osm_candidate_m: geom.centroid(1).distance(osmUnion, 1)
      });
    });
  }

  if (drawPreview) {
    Map.centerObject(cityGeometry, 10);
    Map.addLayer(cityGeometry, {color: 'yellow'}, cityName + ' study area');
    Map.addLayer(featureImage, {bands: ['s2_B4', 's2_B3', 's2_B2'], min: 0.02, max: 0.25}, cityName + ' S2 true colour');
    Map.addLayer(featureImage.select('builtup').selfMask(), {palette: ['ff9900']}, cityName + ' built-up');
    Map.addLayer(featureImage.select('urban_surrounding_1km'), {min: 0, max: 1, palette: ['white', 'orange', 'red']}, cityName + ' urban surrounding 1km');
    Map.addLayer(featureImage.select('s2_swir_glcm_contrast'), {min: 0, max: 200, palette: ['white', 'yellow', 'orange', 'red', 'purple']}, cityName + ' SWIR GLCM contrast');
    Map.addLayer(featureImage.select('s2_ndvi'), {min: -0.1, max: 0.6, palette: ['brown', 'white', 'green']}, cityName + ' annual NDVI');
    Map.addLayer(grid.style({color: 'white', fillColor: '00000000', width: 1}), {}, cityName + ' 250m UTM grid');
    print(cityName + ' feature preview', gridFeatures.limit(5));
    print(cityName + ' grid count', gridFeatures.size());
  }

  Export.table.toDrive({
    collection: gridFeatures,
    description: 'book1_grid_features_' + cityName + '_' + YEAR,
    folder: EXPORT_FOLDER,
    fileNamePrefix: 'book1_grid_features_' + cityName + '_' + YEAR,
    fileFormat: 'CSV'
  });
}

// ----------------------------- RUN EXPORTS ----------------------------------
// This final block schedules the export task(s). GEE does not immediately write
// files when this script runs; it creates tasks in the Tasks panel, which must
// be started by the user.

print('Cities scheduled for export:', CITIES_TO_EXPORT);
print('Export folder:', EXPORT_FOLDER);
print('Grid size:', GRID_SIZE_M, 'metres, city-specific UTM projection');
print('Built-up export threshold:', MIN_BUILTUP_FRACTION_FOR_EXPORT);

CITIES_TO_EXPORT.forEach(function(cityName, idx) {
  exportCity(cityName, idx === 0);
});
